import com.github.spotbugs.SpotBugsTask

buildscript {
	ext {
		springBootVersion = '2.3.0.RELEASE'
	}
	repositories {
		mavenCentral()
		jcenter()
	}
	dependencies {
		classpath "org.springframework.boot:spring-boot-gradle-plugin:${springBootVersion}"
		classpath 'org.jfrog.buildinfo:build-info-extractor-gradle:4.7.2'
	}
}

plugins {
	id 'java'
	id 'idea'
	id 'maven'
	id 'maven-publish'
		id 'io.spring.dependency-management' version '1.0.6.RELEASE'
	id 'jacoco'
	id 'com.jfrog.artifactory' version '4.8.1'
	id 'org.ajoberstar.grgit' version '3.0.0'
	id 'com.github.spotbugs' version '1.6.5'
}

description = 'census31-fwmt-storage-utils'

group = 'uk.gov.ons.census.ffa'

version = rootProject.file('version.txt').text.trim()

sourceCompatibility = '11'

targetCompatibility = '11'

repositories {
	mavenLocal()
	mavenCentral()
		maven {
       		url 'https://ons.jfrog.io/ons/libs-releases-virtual'
        	credentials {
            	username "${artifactory_user}"
            	password "${artifactory_password}"
        	}
    	}
    	maven {
        	url 'https://ons.jfrog.io/ons/libs-snapshots-virtual'
        	credentials {
            	username "${artifactory_user}"
            	password "${artifactory_password}"
        	}
    	}}

dependencies {
compile group: 'org.projectlombok', name: 'lombok', version: '1.18.10'
annotationProcessor group: 'org.projectlombok', name: 'lombok', version: '1.18.10'
	compile group: 'commons-io', name: 'commons-io', version: '2.6'
	implementation('com.google.cloud:google-cloud-nio:0.120.0-alpha')
// https://mvnrepository.com/artifact/org.springframework/spring-core
compile group: 'org.springframework', name: 'spring-beans', version: '5.2.6.RELEASE'
// https://mvnrepository.com/artifact/org.springframework/spring-context
compile group: 'org.springframework', name: 'spring-context', version: '5.2.6.RELEASE'


}

dependencyManagement {
	imports {
		mavenBom "org.springframework.cloud:spring-cloud-dependencies:Greenwich.SR1"
	}
}

jacoco {
	toolVersion = "0.8.2"
}

jacocoTestReport {
	reports {
		xml.enabled true
		html.enabled false
	}
}

test.finalizedBy(project.tasks.jacocoTestReport)

/*
processResources {
    filter ReplaceTokens, tokens: [
            'project.artifactId': 'name',
            'project.version'   : 'version',
            'scm.url'           : 'url',
            'buildNumber'       : 'buildnumber',
            'scmBranch'         : 'branch',
            'timestamp'         : 'timestamp',
    ]
}
*/

artifactory {
    contextUrl = 'https://ons.jfrog.io/ons/'
    publish {
        repository {
            repoKey = 'libs-releases-local'
            username = "${artifactory_user}"
            password = "${artifactory_password}"
        }
        defaults {
            publishBuildInfo = false
        }
    }
}

publishing {
	publications {
		maven(MavenPublication) {
			groupId = group
			artifactId = 'census31-fwmt-storage-utils'
			version = version

			from components.java
		}
	}
}

artifactoryPublish {
	publications 'maven'
}

spotbugs {
	toolVersion = '3.1.9'
}

tasks.withType(SpotBugsTask) {
	reports {
		xml.enabled = false
		html.enabled = true
	}
}

